name: Standard Matrix Unit Test
on:
  pull_request:
  push:
  schedule:
    - cron: '*/17280 * * * *'
jobs:
  Explore-GitHub-Actions:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - run: git submodule update --init --recursive
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server"
      - run: echo "ğŸ” Branch Name ${{ github.ref }} and Repo Name ${{ github.repository }}."
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test code on the runner."
      - name: echo "Run configure script"
        run: |
           cd Test
           sh configure.sh
      - name: echo "Run generate script"
        run: |
          cd Test
          sh generate.sh
      - name: echo "Run unit tests procedure"
        run: |
          cd Test
          sh run.sh
      - run: echo "ğŸ This job's status is ${{ job.status }}."
